config/routes.rb
Rails.application.routes.draw do
  get 'create/index'
  namespace :api do
    namespace :v1 do
      resources :candidates, :voters, defaults: { :format => 'json' }
    end
  end
  resources :voters

  resources :candidates

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/models/voter.rb
class Voter < ActiveRecord::Base
end

app/controllers/api/v1/candidates_controller.rb
class Api::V1::CandidatesController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    render json: Candidate.all
  end

  def show
    @candidate = Candidate.find(params[:id])
    render json: @candidate
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      render json: @candidate
    else
      render json: "Invalid parameters"
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  private def candidate_params
    params.require(:candidate).permit(:name, :party)
  end
end

app/controllers/api/v1/voters_controller.rb
class Api::V1::VotersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    render json: Voter.all
  end

  def show
    @voter = Voters.find(params[:id])
    render json: @voter
  end

  def create
    @voter = Voters.new(voter_params)

    if @voter.save
      render json: @voter
    else
      render json: "Invalid parameters"
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  private def voter_params
    params.require(:voter).permit(:name, :party)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to @candidate, notice: 'Candidate was successfully created.' }
    else
      render :new
    end
  end


  # PATCH/PUT /candidates/1
  def update
    if @candidate.update(candidate_params)
      redirect_to @candidate, notice: 'Candidate was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :party)
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(voter_params)

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render :show, status: :created, location: @voter }
      else
        format.html { render :new }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voters/1
  # PATCH/PUT /voters/1.json
  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { render :show, status: :ok, location: @voter }
      else
        format.html { render :edit }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter.destroy
    respond_to do |format|
      format.html { redirect_to voters_url, notice: 'Voter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voter_params
      params.require(:voter).permit(:name, :party)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.party %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Party:</strong>
  <%= @candidate.party %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/create/index.html.erb
<h1>Create#index</h1>
<p>Find me in app/views/create/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VotingApiSol</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing Voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= voter.name %></td>
        <td><%= voter.party %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voter', new_voter_path %>

app/views/voters/new.html.erb
<h1>New Voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voter.name %>
</p>

<p>
  <strong>Party:</strong>
  <%= @voter.party %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>